# Generated by Django 4.2.5 on 2023-09-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_country_country_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_id',
        ),
    ]
