# Generated by Django 4.2.5 on 2023-10-20 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenities', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenities.amenity')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
            options={
                'unique_together': {('amenity', 'ticket')},
            },
        ),
    ]
