# Generated by Django 4.2.5 on 2023-10-20 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenities', '0001_initial'),
        ('cabintypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinTypeAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenities.amenity')),
                ('cabin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabintypes.cabintype')),
            ],
            options={
                'unique_together': {('cabin_type', 'amenity')},
            },
        ),
    ]
