# Generated by Django 4.2.5 on 2023-10-20 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
        ('airoutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='ArrivalAirport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_routes', to='airports.airport'),
        ),
        migrations.AddField(
            model_name='route',
            name='DepartureAirport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_routes', to='airports.airport'),
        ),
    ]
