# Generated by Django 4.2.5 on 2023-10-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_id',
        ),
    ]
