# Generated by Django 4.2.5 on 2023-09-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_birthday_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Определяет, может ли пользователь пользоваться инфраструктурой Employee', verbose_name='Employee status'),
        ),
    ]
