# Generated by Django 4.2.5 on 2023-10-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_logout_times',
            field=models.JSONField(blank=True, null=True, verbose_name='Время входа и выхода'),
        ),
    ]
