# Generated by Django 4.2.5 on 2023-10-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_remove_role_role_id'),
        ('authentication', '0007_user_login_logout_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.role'),
        ),
    ]
