# Generated by Django 4.2.5 on 2023-09-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_office_country_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='user_id',
        ),
    ]
