# Generated by Django 4.2.5 on 2023-10-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Месяц опроса'),
        ),
    ]
