# Generated by Django 4.2.5 on 2023-10-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='date',
            new_name='mounth',
        ),
    ]
