# Generated by Django 4.2.5 on 2023-10-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_rename_date_survey_mounth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='mounth',
            new_name='month',
        ),
    ]
