# Generated by Django 4.2.5 on 2023-10-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_survey_age_alter_survey_q1_alter_survey_q2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
